# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(307, 208)
        MainWindow.setStyleSheet("QTabBar::tab {\n"
"    padding: 5px;\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CB_event1 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CB_event1.setFont(font)
        self.CB_event1.setObjectName("CB_event1")
        self.verticalLayout_2.addWidget(self.CB_event1)
        self.CB_event2 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CB_event2.setFont(font)
        self.CB_event2.setObjectName("CB_event2")
        self.verticalLayout_2.addWidget(self.CB_event2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout_2.addWidget(self.dateTimeEdit)
        self.PB_save = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PB_save.setFont(font)
        self.PB_save.setObjectName("PB_save")
        self.verticalLayout_2.addWidget(self.PB_save)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.PB_add = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PB_add.setFont(font)
        self.PB_add.setObjectName("PB_add")
        self.gridLayout.addWidget(self.PB_add, 0, 2, 1, 1)
        self.PB_subtract = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PB_subtract.setFont(font)
        self.PB_subtract.setObjectName("PB_subtract")
        self.gridLayout.addWidget(self.PB_subtract, 0, 0, 1, 1)
        self.L_money = QtWidgets.QLabel(self.tab_2)
        self.L_money.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.L_money.setFont(font)
        self.L_money.setAlignment(QtCore.Qt.AlignCenter)
        self.L_money.setObjectName("L_money")
        self.gridLayout.addWidget(self.L_money, 0, 1, 1, 1)
        self.LE_money = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LE_money.setFont(font)
        self.LE_money.setObjectName("LE_money")
        self.gridLayout.addWidget(self.LE_money, 1, 0, 1, 1)
        self.PB_pay = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PB_pay.setFont(font)
        self.PB_pay.setObjectName("PB_pay")
        self.gridLayout.addWidget(self.PB_pay, 1, 1, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Little Helper :)"))
        self.CB_event1.setText(_translate("MainWindow", "Event 1"))
        self.CB_event2.setText(_translate("MainWindow", "Event 2"))
        self.PB_save.setText(_translate("MainWindow", "Save This"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Events"))
        self.PB_add.setText(_translate("MainWindow", "+1"))
        self.PB_subtract.setText(_translate("MainWindow", "-1"))
        self.L_money.setText(_translate("MainWindow", "- nn,nn €"))
        self.PB_pay.setText(_translate("MainWindow", "Pay"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Coffee"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

